name: build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: null2264/actions/gradle-setup@6712f98d592b126629afd27dc4870c93b53426b4
        with:
          java: 17

      - name: Build with Gradle
        run: ./gradlew build --stacktrace

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: Results
          path: build/reports/
