name: build
on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        java: [
          8,
          17
        ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build --stacktrace
      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: Results
          path: build/reports/
